sudo: required
language: ruby
rvm:
- 2.7.0
script:
- "bundle exec rspec"
notifications:
  slack:
    rooms:
      secure: sgXX8c9YRtwmCVWC60M/LlZMAvyGudfqqMurGK4CFtKFNKM5fJtes0Bmk3ZNthxKN0TOjq86EzDnV7LOLlEeDQHujB+BTEO3/gzqfM9ms7HPaBRU2QraPeyvnYdBFTlfGVidT65k1+67tZmrNVpQN+UreXK5t7kEXNWw6IgKDkZ9F2Go7V1DmDXCR+xqeeyPrQgeA4iO6TQ9V/UHNH8q6oqAibTI8sJQSboGNeigp92UKkLTuFEF+WMBwWbViVMLsPSRe2ZYxkIugvPF96q0u6tEfWW7QYB1Vrr+enRKxarL9smk5nmXhJLJsyK8GY7YNQn6xPgU4fEivWOAHVj49VJo8X8blvz5Fgy+smXdLRWnHxxVC0PvNNMDO+Wf5KlKGe4lQXXRcCAh6dP7E4RtW2QA3eDZO9K7WNpQTwi+5jL0EcqGspyxzL1DZ4ULOU3aLw62u4mm39p/YWd1vCO9nVWEwHGJ28oMnHgiU0hqO2Va0KukXfgILT25Ft5gwdvIUiyYtYWOUj6yUp/ro3sK922F3mHZYCVZS6JLbuvt5bnAqMioo7qJug5f5O1TcN6JXVJ8l+jFey7XF+ivrXWCb6o2J6t6XE+HXC2hZXPCA0VQQyvKhhpQxGt4XMYevlp8YVR9RnvvEr+UZ6HE4SKzy6pX9ywLkWGRaOENWUS/cEQ=
